server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/studentservice,classpath:/config/organizationservice
        git:
          uri: https://git.onedatasoftware.com/flexvpc/solar-world-config.git
          searchPaths: studentservice
          username: gitlab+deploy-token-2
          password: us_-dRD4gnpDaynbbhpa






